import { useEffect, useState } from 'react'
import type { AppointmentRow } from '../../types/dashboard'

type AppointmentFormModalProps = {
  isOpen: boolean
  onClose: () => void
  onSubmit: (data: AppointmentRow) => Promise<void>
  /** When provided the form is in "Edit" mode and fields are pre-filled. */
  initialData?: AppointmentRow | null
  isSubmitting?: boolean
}

type AppointmentFormData = Omit<AppointmentRow, 'code' | 'status'>

type FormErrors = Partial<Record<keyof AppointmentFormData, string>>

const SERVICE_OPTIONS = [
  'Business Permit Endorsement',
  'Barangay Clearance',
  'Certificate Claim',
  'Blotter Follow-up',
  'Indigency Certificate',
  'Residency Certificate',
  'General Inquiry',
  'Complaint Filing',
]

const emptyForm: AppointmentFormData = {
  resident: '',
  service: '',
  schedule: new Date().toISOString().slice(0, 16),
}

export function AppointmentFormModal({
  isOpen,
  onClose,
  onSubmit,
  initialData,
  isSubmitting = false,
}: AppointmentFormModalProps) {
  const isEditMode = Boolean(initialData)
  const [form, setForm] = useState<AppointmentFormData>(emptyForm)
  const [errors, setErrors] = useState<FormErrors>({})

  // Reset form whenever the modal opens or initialData changes
  useEffect(() => {
    if (isOpen) {
      if (initialData) {
        setForm({
          resident: initialData.resident,
          service: initialData.service,
          schedule: initialData.schedule,
        })
      } else {
        setForm({
          ...emptyForm,
          schedule: new Date().toISOString().slice(0, 16),
        })
      }
      setErrors({})
    }
  }, [isOpen, initialData])

  function validate(): FormErrors {
    const e: FormErrors = {}

    if (!form.resident.trim()) {
      e.resident = 'Resident name is required.'
    } else if (form.resident.trim().length < 2) {
      e.resident = 'Name must be at least 2 characters.'
    }

    if (!form.service) {
      e.service = 'Service is required.'
    }

    if (!form.schedule) {
      e.schedule = 'Schedule date and time are required.'
    }

    return e
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    const validationErrors = validate()
    setErrors(validationErrors)

    if (Object.keys(validationErrors).length > 0) return

    const payload: AppointmentRow = {
      code: initialData?.code ?? '', // Will be generated by service for new records
      resident: form.resident.trim(),
      service: form.service,
      schedule: form.schedule,
      status: initialData?.status ?? 'Pending',
    }

    await onSubmit(payload)
  }

  if (!isOpen) return null

  const inputBaseClass =
    'w-full rounded-lg border px-3 py-2 text-sm outline-none transition'
  const inputNormalClass =
    'border-slate-300 focus:border-indigo-400 focus:ring-2 focus:ring-indigo-200 dark:border-slate-600 dark:bg-slate-700 dark:text-slate-100'
  const inputErrorClass = 'border-rose-400 focus:ring-2 focus:ring-rose-300'

  return (
    // Backdrop
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"
      onClick={onClose}
    >
      {/* Modal */}
      <div
        className="w-full max-w-md rounded-xl bg-white shadow-2xl dark:bg-slate-800"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between border-b border-slate-200 px-6 py-4 dark:border-slate-700">
          <h2 className="text-lg font-semibold text-slate-800 dark:text-slate-100">
            {isEditMode ? 'Edit Appointment' : 'Schedule Appointment'}
          </h2>
          <button
            type="button"
            onClick={onClose}
            className="rounded-lg p-1 text-slate-400 hover:bg-slate-100 hover:text-slate-600 dark:hover:bg-slate-700 dark:hover:text-slate-300"
          >
            <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="space-y-4 px-6 py-5">
          {/* Resident */}
          <div>
            <label
              htmlFor="apt-resident"
              className="mb-1 block text-sm font-medium text-slate-700 dark:text-slate-300"
            >
              Resident Name <span className="text-rose-500">*</span>
            </label>
            <input
              id="apt-resident"
              type="text"
              value={form.resident}
              onChange={(e) => setForm({ ...form, resident: e.target.value })}
              placeholder="e.g. Juan Dela Cruz"
              className={`${inputBaseClass} ${errors.resident ? inputErrorClass : inputNormalClass}`}
            />
            {errors.resident && <p className="mt-1 text-xs text-rose-500">{errors.resident}</p>}
          </div>

          {/* Service */}
          <div>
            <label
              htmlFor="apt-service"
              className="mb-1 block text-sm font-medium text-slate-700 dark:text-slate-300"
            >
              Service <span className="text-rose-500">*</span>
            </label>
            <select
              id="apt-service"
              value={form.service}
              onChange={(e) => setForm({ ...form, service: e.target.value })}
              className={`${inputBaseClass} ${errors.service ? inputErrorClass : inputNormalClass}`}
            >
              <option value="">Select Service</option>
              {SERVICE_OPTIONS.map((svc) => (
                <option key={svc} value={svc}>
                  {svc}
                </option>
              ))}
            </select>
            {errors.service && <p className="mt-1 text-xs text-rose-500">{errors.service}</p>}
          </div>

          {/* Schedule Date and Time */}
          <div>
            <label
              htmlFor="apt-schedule"
              className="mb-1 block text-sm font-medium text-slate-700 dark:text-slate-300"
            >
              Schedule <span className="text-rose-500">*</span>
            </label>
            <input
              id="apt-schedule"
              type="datetime-local"
              value={form.schedule}
              onChange={(e) => setForm({ ...form, schedule: e.target.value })}
              className={`${inputBaseClass} ${errors.schedule ? inputErrorClass : inputNormalClass}`}
            />
            {errors.schedule && <p className="mt-1 text-xs text-rose-500">{errors.schedule}</p>}
          </div>

          {/* Actions */}
          <div className="flex items-center justify-end gap-3 pt-2">
            <button
              type="button"
              onClick={onClose}
              disabled={isSubmitting}
              className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50 dark:border-slate-600 dark:text-slate-300 dark:hover:bg-slate-700"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={isSubmitting}
              className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-700 disabled:opacity-60"
            >
              {isSubmitting && (
                <svg className="h-4 w-4 animate-spin" viewBox="0 0 24 24" fill="none">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v4a4 4 0 00-4 4H4z" />
                </svg>
              )}
              {isEditMode ? 'Save Changes' : 'Schedule Appointment'}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}
