import { useEffect, useState } from 'react'
import type { BlotterRow } from '../../types/dashboard'

type BlotterFormModalProps = {
  isOpen: boolean
  onClose: () => void
  onSubmit: (data: BlotterRow) => Promise<void>
  /** When provided the form is in "Edit" mode and fields are pre-filled. */
  initialData?: BlotterRow | null
  isSubmitting?: boolean
}

type BlotterFormData = Omit<BlotterRow, 'code' | 'status'>

type FormErrors = Partial<Record<keyof BlotterFormData, string>>

const INCIDENT_TYPES = [
  'Noise Complaint',
  'Boundary Dispute',
  'Public Disturbance',
  'Theft',
  'Physical Assault',
  'Verbal Abuse',
  'Property Damage',
  'Domestic Violence',
  'Trespassing',
  'Other',
]

const emptyForm: BlotterFormData = {
  complainant: '',
  respondent: '',
  incident: '',
  incidentDetails: '',
  incidentDate: new Date().toISOString().slice(0, 10),
}

export function BlotterFormModal({
  isOpen,
  onClose,
  onSubmit,
  initialData,
  isSubmitting = false,
}: BlotterFormModalProps) {
  const isEditMode = Boolean(initialData)
  const [form, setForm] = useState<BlotterFormData>(emptyForm)
  const [errors, setErrors] = useState<FormErrors>({})

  // Reset form whenever the modal opens or initialData changes
  useEffect(() => {
    if (isOpen) {
      if (initialData) {
        setForm({
          complainant: initialData.complainant,
          respondent: initialData.respondent,
          incident: initialData.incident,
          incidentDetails: initialData.incidentDetails,
          incidentDate: initialData.incidentDate,
        })
      } else {
        setForm({ ...emptyForm, incidentDate: new Date().toISOString().slice(0, 10) })
      }
      setErrors({})
    }
  }, [isOpen, initialData])

  function validate(): FormErrors {
    const e: FormErrors = {}

    if (!form.complainant.trim()) {
      e.complainant = 'Complainant name is required.'
    } else if (form.complainant.trim().length < 2) {
      e.complainant = 'Name must be at least 2 characters.'
    }

    if (!form.respondent.trim()) {
      e.respondent = 'Respondent name is required.'
    } else if (form.respondent.trim().length < 2) {
      e.respondent = 'Name must be at least 2 characters.'
    }

    if (!form.incident) {
      e.incident = 'Incident type is required.'
    }

    if (!form.incidentDetails.trim()) {
      e.incidentDetails = 'Incident details are required.'
    } else if (form.incidentDetails.trim().length < 10) {
      e.incidentDetails = 'Please provide at least 10 characters of detail.'
    }

    if (!form.incidentDate) {
      e.incidentDate = 'Incident date is required.'
    }

    return e
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    const validationErrors = validate()
    setErrors(validationErrors)

    if (Object.keys(validationErrors).length > 0) return

    const payload: BlotterRow = {
      code: initialData?.code ?? '', // Will be generated by service for new records
      complainant: form.complainant.trim(),
      respondent: form.respondent.trim(),
      incident: form.incident,
      incidentDetails: form.incidentDetails.trim(),
      incidentDate: form.incidentDate,
      status: initialData?.status ?? 'Filed',
    }

    await onSubmit(payload)
  }

  if (!isOpen) return null

  const inputBaseClass =
    'w-full rounded-lg border px-3 py-2 text-sm outline-none transition'
  const inputNormalClass =
    'border-slate-300 focus:border-indigo-400 focus:ring-2 focus:ring-indigo-200 dark:border-slate-600 dark:bg-slate-700 dark:text-slate-100'
  const inputErrorClass = 'border-rose-400 focus:ring-2 focus:ring-rose-300'

  return (
    // Backdrop
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"
      onClick={onClose}
    >
      {/* Modal */}
      <div
        className="w-full max-w-lg rounded-xl bg-white shadow-2xl dark:bg-slate-800"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between border-b border-slate-200 px-6 py-4 dark:border-slate-700">
          <h2 className="text-lg font-semibold text-slate-800 dark:text-slate-100">
            {isEditMode ? 'Edit Blotter Record' : 'File Blotter'}
          </h2>
          <button
            type="button"
            onClick={onClose}
            className="rounded-lg p-1 text-slate-400 hover:bg-slate-100 hover:text-slate-600 dark:hover:bg-slate-700 dark:hover:text-slate-300"
          >
            <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="space-y-4 px-6 py-5">
          {/* Complainant */}
          <div>
            <label
              htmlFor="blotter-complainant"
              className="mb-1 block text-sm font-medium text-slate-700 dark:text-slate-300"
            >
              Complainant <span className="text-rose-500">*</span>
            </label>
            <input
              id="blotter-complainant"
              type="text"
              value={form.complainant}
              onChange={(e) => setForm({ ...form, complainant: e.target.value })}
              placeholder="e.g. Juan Dela Cruz"
              className={`${inputBaseClass} ${errors.complainant ? inputErrorClass : inputNormalClass}`}
            />
            {errors.complainant && <p className="mt-1 text-xs text-rose-500">{errors.complainant}</p>}
          </div>

          {/* Respondent */}
          <div>
            <label
              htmlFor="blotter-respondent"
              className="mb-1 block text-sm font-medium text-slate-700 dark:text-slate-300"
            >
              Respondent <span className="text-rose-500">*</span>
            </label>
            <input
              id="blotter-respondent"
              type="text"
              value={form.respondent}
              onChange={(e) => setForm({ ...form, respondent: e.target.value })}
              placeholder="e.g. Pedro Santos"
              className={`${inputBaseClass} ${errors.respondent ? inputErrorClass : inputNormalClass}`}
            />
            {errors.respondent && <p className="mt-1 text-xs text-rose-500">{errors.respondent}</p>}
          </div>

          {/* Incident Type */}
          <div>
            <label
              htmlFor="blotter-incident"
              className="mb-1 block text-sm font-medium text-slate-700 dark:text-slate-300"
            >
              Incident Type <span className="text-rose-500">*</span>
            </label>
            <select
              id="blotter-incident"
              value={form.incident}
              onChange={(e) => setForm({ ...form, incident: e.target.value })}
              className={`${inputBaseClass} ${errors.incident ? inputErrorClass : inputNormalClass}`}
            >
              <option value="">Select Incident Type</option>
              {INCIDENT_TYPES.map((t) => (
                <option key={t} value={t}>
                  {t}
                </option>
              ))}
            </select>
            {errors.incident && <p className="mt-1 text-xs text-rose-500">{errors.incident}</p>}
          </div>

          {/* Incident Date */}
          <div>
            <label
              htmlFor="blotter-date"
              className="mb-1 block text-sm font-medium text-slate-700 dark:text-slate-300"
            >
              Incident Date <span className="text-rose-500">*</span>
            </label>
            <input
              id="blotter-date"
              type="date"
              value={form.incidentDate}
              onChange={(e) => setForm({ ...form, incidentDate: e.target.value })}
              className={`${inputBaseClass} ${errors.incidentDate ? inputErrorClass : inputNormalClass}`}
            />
            {errors.incidentDate && <p className="mt-1 text-xs text-rose-500">{errors.incidentDate}</p>}
          </div>

          {/* Incident Details */}
          <div>
            <label
              htmlFor="blotter-details"
              className="mb-1 block text-sm font-medium text-slate-700 dark:text-slate-300"
            >
              Incident Details <span className="text-rose-500">*</span>
            </label>
            <textarea
              id="blotter-details"
              rows={4}
              value={form.incidentDetails}
              onChange={(e) => setForm({ ...form, incidentDetails: e.target.value })}
              placeholder="Describe what happened in detail..."
              className={`${inputBaseClass} resize-none ${errors.incidentDetails ? inputErrorClass : inputNormalClass}`}
            />
            {errors.incidentDetails && (
              <p className="mt-1 text-xs text-rose-500">{errors.incidentDetails}</p>
            )}
          </div>

          {/* Actions */}
          <div className="flex items-center justify-end gap-3 pt-2">
            <button
              type="button"
              onClick={onClose}
              disabled={isSubmitting}
              className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50 dark:border-slate-600 dark:text-slate-300 dark:hover:bg-slate-700"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={isSubmitting}
              className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-700 disabled:opacity-60"
            >
              {isSubmitting && (
                <svg className="h-4 w-4 animate-spin" viewBox="0 0 24 24" fill="none">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v4a4 4 0 00-4 4H4z" />
                </svg>
              )}
              {isEditMode ? 'Save Changes' : 'File Blotter'}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}
