import { useEffect, useState } from 'react'
import type { UserRow, UserRole } from '../../types/dashboard'

type UserFormModalProps = {
  isOpen: boolean
  onClose: () => void
  onSubmit: (data: UserRow) => Promise<void>
  /** When provided the form is in "Edit" mode and fields are pre-filled. */
  initialData?: UserRow | null
  isSubmitting?: boolean
}

type UserFormData = Omit<UserRow, 'id' | 'status'>

type FormErrors = Partial<Record<keyof UserFormData, string>>

const ROLE_OPTIONS: { label: string; value: UserRole }[] = [
  { label: 'Admin', value: 'admin' },
  { label: 'Staff', value: 'staff' },
  { label: 'Approver', value: 'approver' },
  { label: 'Resident', value: 'resident' },
]

const emptyForm: UserFormData = {
  name: '',
  email: '',
  role: 'staff',
}

export function UserFormModal({
  isOpen,
  onClose,
  onSubmit,
  initialData,
  isSubmitting = false,
}: UserFormModalProps) {
  const isEditMode = Boolean(initialData)
  const [form, setForm] = useState<UserFormData>(emptyForm)
  const [errors, setErrors] = useState<FormErrors>({})

  // Reset form whenever the modal opens or initialData changes
  useEffect(() => {
    if (isOpen) {
      if (initialData) {
        setForm({
          name: initialData.name,
          email: initialData.email,
          role: initialData.role,
        })
      } else {
        setForm(emptyForm)
      }
      setErrors({})
    }
  }, [isOpen, initialData])

  function validate(): FormErrors {
    const e: FormErrors = {}

    if (!form.name.trim()) {
      e.name = 'Name is required.'
    } else if (form.name.trim().length < 2) {
      e.name = 'Name must be at least 2 characters.'
    }

    if (!form.email.trim()) {
      e.email = 'Email is required.'
    } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)) {
      e.email = 'Please enter a valid email address.'
    }

    if (!form.role) {
      e.role = 'Role is required.'
    }

    return e
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    const validationErrors = validate()
    setErrors(validationErrors)

    if (Object.keys(validationErrors).length > 0) return

    const payload: UserRow = {
      id: initialData?.id ?? '', // Will be generated by service for new records
      name: form.name.trim(),
      email: form.email.trim(),
      role: form.role,
      status: initialData?.status ?? 'Active',
    }

    await onSubmit(payload)
  }

  if (!isOpen) return null

  const inputBaseClass =
    'w-full rounded-lg border px-3 py-2 text-sm outline-none transition'
  const inputNormalClass =
    'border-slate-300 focus:border-indigo-400 focus:ring-2 focus:ring-indigo-200 dark:border-slate-600 dark:bg-slate-700 dark:text-slate-100'
  const inputErrorClass = 'border-rose-400 focus:ring-2 focus:ring-rose-300'

  return (
    // Backdrop
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"
      onClick={onClose}
    >
      {/* Modal */}
      <div
        className="w-full max-w-md rounded-xl bg-white shadow-2xl dark:bg-slate-800"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between border-b border-slate-200 px-6 py-4 dark:border-slate-700">
          <h2 className="text-lg font-semibold text-slate-800 dark:text-slate-100">
            {isEditMode ? 'Edit User' : 'Add User'}
          </h2>
          <button
            type="button"
            onClick={onClose}
            className="rounded-lg p-1 text-slate-400 hover:bg-slate-100 hover:text-slate-600 dark:hover:bg-slate-700 dark:hover:text-slate-300"
          >
            <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="space-y-4 px-6 py-5">
          {/* Name */}
          <div>
            <label
              htmlFor="user-name"
              className="mb-1 block text-sm font-medium text-slate-700 dark:text-slate-300"
            >
              Full Name <span className="text-rose-500">*</span>
            </label>
            <input
              id="user-name"
              type="text"
              value={form.name}
              onChange={(e) => setForm({ ...form, name: e.target.value })}
              placeholder="e.g. Juan Dela Cruz"
              className={`${inputBaseClass} ${errors.name ? inputErrorClass : inputNormalClass}`}
            />
            {errors.name && <p className="mt-1 text-xs text-rose-500">{errors.name}</p>}
          </div>

          {/* Email */}
          <div>
            <label
              htmlFor="user-email"
              className="mb-1 block text-sm font-medium text-slate-700 dark:text-slate-300"
            >
              Email <span className="text-rose-500">*</span>
            </label>
            <input
              id="user-email"
              type="email"
              value={form.email}
              onChange={(e) => setForm({ ...form, email: e.target.value })}
              placeholder="e.g. juan@barangay.gov.ph"
              className={`${inputBaseClass} ${errors.email ? inputErrorClass : inputNormalClass}`}
            />
            {errors.email && <p className="mt-1 text-xs text-rose-500">{errors.email}</p>}
          </div>

          {/* Role */}
          <div>
            <label
              htmlFor="user-role"
              className="mb-1 block text-sm font-medium text-slate-700 dark:text-slate-300"
            >
              Role <span className="text-rose-500">*</span>
            </label>
            <select
              id="user-role"
              value={form.role}
              onChange={(e) => setForm({ ...form, role: e.target.value as UserRole })}
              className={`${inputBaseClass} ${errors.role ? inputErrorClass : inputNormalClass}`}
            >
              <option value="">Select Role</option>
              {ROLE_OPTIONS.map((opt) => (
                <option key={opt.value} value={opt.value}>
                  {opt.label}
                </option>
              ))}
            </select>
            {errors.role && <p className="mt-1 text-xs text-rose-500">{errors.role}</p>}
          </div>

          {/* Actions */}
          <div className="flex items-center justify-end gap-3 pt-2">
            <button
              type="button"
              onClick={onClose}
              disabled={isSubmitting}
              className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50 dark:border-slate-600 dark:text-slate-300 dark:hover:bg-slate-700"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={isSubmitting}
              className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-700 disabled:opacity-60"
            >
              {isSubmitting && (
                <svg className="h-4 w-4 animate-spin" viewBox="0 0 24 24" fill="none">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v4a4 4 0 00-4 4H4z" />
                </svg>
              )}
              {isEditMode ? 'Save Changes' : 'Add User'}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}
